name: 'Release Info Action'
author: 'Aaron Batilo'
description: 'An action to read release information of a given GitHub repository'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'package'
  color: 'gray-dark'
inputs:
  owner:
    description: 'The user or org for this repo'
    required: true
  repo:
    description: 'The name of the repo itself'
    required: true
outputs:
  latest_tag:
    description: 'The latest release version tag'
  latest_tag_published_at:
    description: 'The ISO8601 timestamp of when this version was released'
