on: push

name: ci
jobs:
  ci:
    name: Get Latest Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get Latest Release
      uses: ./
      with:
        owner: abatilo
        repo: release-info-action
  release:
    name: Release this project
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12
    - name: Generate release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
