on: push

name: ci
jobs:
  ci:
    name: Get Latest Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get Latest Release
      uses: ./
      with:
        owner: abatilo
        repo: release-info-action
