on:
  push:
    branches:
      - master

name: Release
jobs:
  release:
    name: Release this project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 12
    - name: Install
      run: npm ci
    - name: Generate release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run semantic-release
